spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/volume?serverTimezone=Asia/Seoul
    username: volume_tester
    password: volumetester
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  servlet:
    multipart:
      location: C://Users/tiger/OneDrive/문서/volume/volume/Users